### PR TITLE
Added '-i' option to specify network interface

### PR DESCRIPTION
**Pull request by vzaliva**
Fixes https://github.com/andreikop/python-ws-discovery/issues/21

### CODE REVIEW

**Comment by andreikop** [comment]
Hi.
Sorry for a slow reply.

I checked the code and found that interfaces are detected but not used by the script.
Can't we just remove this interface detection?

**Comment by vzaliva** [comment]
sure. with this option added you can remove automatic interface detection.

**Comment by andreikop** [comment]
It seems like I can remove interface selection even wo this PR.
`ipaddr` variable is set but never used.
I don't know why, haven't checked the history of the file.

**Comment by vzaliva** [comment]
wait. How could it work without interface?! it needs to listen for broadcasts.

**Comment by andreikop** [comment]
I also don't know. I'm not a original author, I just passively maintain the project by accepting PRs.
If you have time to check what happens, it would be cool.
It seems like this interface detection code is on it's place for historical reasons. Check git history.

**Comment by vzaliva** [comment]
OK, my socket API knowledge was little rusty but I checked and here what I think: right now it binds to a mulicast group and received packets routed via any interface. It is *possibe* to narrow it down to the particular interface but it is not implemented now in you python code. I think it unnecessary though. I suggest removing all interface handling code since it is now doing anything right now.

**Comment by andreikop** [comment]
Yes, probably.
See also #23

**Comment by andreikop** [comment]
@vzaliva , could you test if #24 works for you?

**Comment by vzaliva** [comment]
> @vzaliva , could you test if #24 works for you?

Yes, it works

**Pull request closed without merging**
