### PR TITLE
Fix unit test on Windows.

### PR DESCRIPTION
**Pull request by jterrace**

### CODE REVIEW

**Comment by wpyoga** [comment]
What is the root cause of the error?

**Comment by jterrace** [comment]
I'm honestly not entirely sure. The error looks like this:

```
selector = <selectors.SelectSelector object at 0x0000013C0E0704A0>
rsock = <socket.socket fd=752, family=2, type=2, proto=0>, evtmask = 1

>       if rsock.getsockname()[1] == MULTICAST_PORT:
E       OSError: [WinError 10022] An invalid argument was supplied

python-ws-discovery\tests\test_probing.py:20: OSError
```

stack trace:
```
python-ws-discovery\wsdiscovery\threaded.py:421: in start
    self._startThreads()
python-ws-discovery\wsdiscovery\threaded.py:396: in _startThreads
    self._addrsMonitorThread_v4 = AddressMonitorThread(self, socket.AF_INET)
python-ws-discovery\wsdiscovery\threaded.py:53: in __init__
    self._updateAddrs()
python-ws-discovery\wsdiscovery\threaded.py:65: in _updateAddrs
    self._wsd._networkAddressAdded(addr)
python-ws-discovery\wsdiscovery\discovery.py:103: in _networkAddressAdded
    self.addSourceAddr(addr)
python-ws-discovery\wsdiscovery\threaded.py:432: in addSourceAddr
    self._networkingThread_v4.addSourceAddr(addr)
python-ws-discovery\wsdiscovery\threaded.py:149: in addSourceAddr
    self._selector.register(sock, selectors.EVENT_READ)
```

I couldn't quite track down exactly why, but it looks like on Windows, the socket is not fully initialized by the time register is called, so calling getsockname is not valid.

**Comment by wpyoga** [comment]
I'm not familiar with Windows, but this might be related: https://stackoverflow.com/questions/43330897/oserror-winerror-10022-an-invalid-argument-was-supplied-windows-10-python

Regardless, I think skipping the exception handling like that will hide the issue and create problems down the line.

**Comment by wpyoga** [comment]
So on Windows, presumably the first comparison will be false, and then the `getsockname()` function won't be called. I think it's okay to do that. Not sure if it will hide any potential issues, maybe someone more senior can take a closer look :)

Also, may I suggest an alternative? Disable this test entirely on Windows, with a comment explaining why. To be honest I can't claim that this solution is better :)

**Comment by jterrace** [comment]
No, I don't think disabling the test is the right thing to do: the test passes on Windows with this fix.

If you look at what the test is doing, it's trying to find the socket that's binding to the multicast port:
https://github.com/andreikop/python-ws-discovery/blob/master/wsdiscovery/threaded.py#L135

This socket uses UDP here:
https://github.com/andreikop/python-ws-discovery/blob/master/wsdiscovery/threaded.py#L129

The problem is the `_createMulticastOutSocket` method also creates a socket with proto 0 here:
https://github.com/andreikop/python-ws-discovery/blob/master/wsdiscovery/threaded.py#L113

which also gets registered with the selector.

On Linux the behavior of `getsockname` is to return all zeros, so the previous test match didn't match port 0:
```
>>> socket.socket(socket.AF_INET, socket.SOCK_DGRAM).getsockname()
('0.0.0.0', 0)
```

On Windows, this throws an exception:

```
>>> socket.socket(socket.AF_INET, socket.SOCK_DGRAM).getsockname()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [WinError 10022] An invalid argument was supplied
```

Adding the UDP proto check makes the test more robust, since it's narrowing the the criteria for which socket it's trying to find.

**Pull request merged**
